baseURL = 'https://badeplatz.ch'
languageCode = 'en-us'
title = 'Badeplatz Ludretikon, Thalwil'

[params]
description = "Badeplatz mit Take Away"  

images = ["/images/cheeseburger.webp"]
copyright = "Peter Wyss"
[markup.goldmark.renderer]
unsafe= true
favicon = "favicon.svg"



