baseURL = 'https://badeplatz.ch'
languageCode = 'en-us'
title = 'Badeplatz Ludretikon, Thalwil'
defaultContentLanguage = 'de'
theme = "hugo-scroll"

[params]
description = "Badeplatz mit Take Away in Thalwil"  
keywords = "Burger, Hausgemachte Pasta, Badeplatz, Zürichsee, Strandbad, Badi, Thalwil, Baden, Essen" 

images = ["/images/cheeseburger.webp"]
copyright = "Peter Wyss"
[markup.goldmark.renderer]
unsafe= true
favicon = "favicon.svg"




